import typing_extensions

from launch_darkly_python_sdk.paths import PathValues
from launch_darkly_python_sdk.apis.paths.api_v2 import ApiV2
from launch_darkly_python_sdk.apis.paths.api_v2_account_relay_auto_configs import ApiV2AccountRelayAutoConfigs
from launch_darkly_python_sdk.apis.paths.api_v2_account_relay_auto_configs_id import ApiV2AccountRelayAutoConfigsId
from launch_darkly_python_sdk.apis.paths.api_v2_account_relay_auto_configs_id_reset import ApiV2AccountRelayAutoConfigsIdReset
from launch_darkly_python_sdk.apis.paths.api_v2_applications import ApiV2Applications
from launch_darkly_python_sdk.apis.paths.api_v2_applications_application_key import ApiV2ApplicationsApplicationKey
from launch_darkly_python_sdk.apis.paths.api_v2_applications_application_key_versions import ApiV2ApplicationsApplicationKeyVersions
from launch_darkly_python_sdk.apis.paths.api_v2_applications_application_key_versions_version_key import ApiV2ApplicationsApplicationKeyVersionsVersionKey
from launch_darkly_python_sdk.apis.paths.api_v2_approval_requests import ApiV2ApprovalRequests
from launch_darkly_python_sdk.apis.paths.api_v2_approval_requests_id import ApiV2ApprovalRequestsId
from launch_darkly_python_sdk.apis.paths.api_v2_approval_requests_id_apply import ApiV2ApprovalRequestsIdApply
from launch_darkly_python_sdk.apis.paths.api_v2_approval_requests_id_reviews import ApiV2ApprovalRequestsIdReviews
from launch_darkly_python_sdk.apis.paths.api_v2_auditlog import ApiV2Auditlog
from launch_darkly_python_sdk.apis.paths.api_v2_auditlog_id import ApiV2AuditlogId
from launch_darkly_python_sdk.apis.paths.api_v2_code_refs_extinctions import ApiV2CodeRefsExtinctions
from launch_darkly_python_sdk.apis.paths.api_v2_code_refs_repositories import ApiV2CodeRefsRepositories
from launch_darkly_python_sdk.apis.paths.api_v2_code_refs_repositories_repo import ApiV2CodeRefsRepositoriesRepo
from launch_darkly_python_sdk.apis.paths.api_v2_code_refs_repositories_repo_branch_delete_tasks import ApiV2CodeRefsRepositoriesRepoBranchDeleteTasks
from launch_darkly_python_sdk.apis.paths.api_v2_code_refs_repositories_repo_branches import ApiV2CodeRefsRepositoriesRepoBranches
from launch_darkly_python_sdk.apis.paths.api_v2_code_refs_repositories_repo_branches_branch import ApiV2CodeRefsRepositoriesRepoBranchesBranch
from launch_darkly_python_sdk.apis.paths.api_v2_code_refs_repositories_repo_branches_branch_extinction_events import ApiV2CodeRefsRepositoriesRepoBranchesBranchExtinctionEvents
from launch_darkly_python_sdk.apis.paths.api_v2_code_refs_statistics import ApiV2CodeRefsStatistics
from launch_darkly_python_sdk.apis.paths.api_v2_code_refs_statistics_project_key import ApiV2CodeRefsStatisticsProjectKey
from launch_darkly_python_sdk.apis.paths.api_v2_destinations import ApiV2Destinations
from launch_darkly_python_sdk.apis.paths.api_v2_destinations_project_key_environment_key import ApiV2DestinationsProjectKeyEnvironmentKey
from launch_darkly_python_sdk.apis.paths.api_v2_destinations_project_key_environment_key_id import ApiV2DestinationsProjectKeyEnvironmentKeyId
from launch_darkly_python_sdk.apis.paths.api_v2_flag_links_projects_project_key_flags_feature_flag_key import ApiV2FlagLinksProjectsProjectKeyFlagsFeatureFlagKey
from launch_darkly_python_sdk.apis.paths.api_v2_flag_links_projects_project_key_flags_feature_flag_key_id import ApiV2FlagLinksProjectsProjectKeyFlagsFeatureFlagKeyId
from launch_darkly_python_sdk.apis.paths.api_v2_flag_status_project_key_feature_flag_key import ApiV2FlagStatusProjectKeyFeatureFlagKey
from launch_darkly_python_sdk.apis.paths.api_v2_flag_statuses_project_key_environment_key import ApiV2FlagStatusesProjectKeyEnvironmentKey
from launch_darkly_python_sdk.apis.paths.api_v2_flag_statuses_project_key_environment_key_feature_flag_key import ApiV2FlagStatusesProjectKeyEnvironmentKeyFeatureFlagKey
from launch_darkly_python_sdk.apis.paths.api_v2_flags_project_key import ApiV2FlagsProjectKey
from launch_darkly_python_sdk.apis.paths.api_v2_flags_project_key_environment_key_feature_flag_key_dependent_flags import ApiV2FlagsProjectKeyEnvironmentKeyFeatureFlagKeyDependentFlags
from launch_darkly_python_sdk.apis.paths.api_v2_flags_project_key_feature_flag_key import ApiV2FlagsProjectKeyFeatureFlagKey
from launch_darkly_python_sdk.apis.paths.api_v2_flags_project_key_feature_flag_key_copy import ApiV2FlagsProjectKeyFeatureFlagKeyCopy
from launch_darkly_python_sdk.apis.paths.api_v2_flags_project_key_feature_flag_key_dependent_flags import ApiV2FlagsProjectKeyFeatureFlagKeyDependentFlags
from launch_darkly_python_sdk.apis.paths.api_v2_flags_project_key_feature_flag_key_experiments_environment_key_metric_key import ApiV2FlagsProjectKeyFeatureFlagKeyExperimentsEnvironmentKeyMetricKey
from launch_darkly_python_sdk.apis.paths.api_v2_flags_project_key_feature_flag_key_expiring_targets_environment_key import ApiV2FlagsProjectKeyFeatureFlagKeyExpiringTargetsEnvironmentKey
from launch_darkly_python_sdk.apis.paths.api_v2_flags_project_key_feature_flag_key_expiring_user_targets_environment_key import ApiV2FlagsProjectKeyFeatureFlagKeyExpiringUserTargetsEnvironmentKey
from launch_darkly_python_sdk.apis.paths.api_v2_flags_project_key_feature_flag_key_triggers_environment_key import ApiV2FlagsProjectKeyFeatureFlagKeyTriggersEnvironmentKey
from launch_darkly_python_sdk.apis.paths.api_v2_flags_project_key_feature_flag_key_triggers_environment_key_id import ApiV2FlagsProjectKeyFeatureFlagKeyTriggersEnvironmentKeyId
from launch_darkly_python_sdk.apis.paths.api_v2_flags_project_key_flag_key_release import ApiV2FlagsProjectKeyFlagKeyRelease
from launch_darkly_python_sdk.apis.paths.api_v2_integration_capabilities_big_segment_store import ApiV2IntegrationCapabilitiesBigSegmentStore
from launch_darkly_python_sdk.apis.paths.api_v2_integration_capabilities_big_segment_store_project_key_environment_key_integration_key import ApiV2IntegrationCapabilitiesBigSegmentStoreProjectKeyEnvironmentKeyIntegrationKey
from launch_darkly_python_sdk.apis.paths.api_v2_integration_capabilities_big_segment_store_project_key_environment_key_integration_key_integration_id import ApiV2IntegrationCapabilitiesBigSegmentStoreProjectKeyEnvironmentKeyIntegrationKeyIntegrationId
from launch_darkly_python_sdk.apis.paths.api_v2_integration_capabilities_feature_store import ApiV2IntegrationCapabilitiesFeatureStore
from launch_darkly_python_sdk.apis.paths.api_v2_integration_capabilities_feature_store_project_key_environment_key import ApiV2IntegrationCapabilitiesFeatureStoreProjectKeyEnvironmentKey
from launch_darkly_python_sdk.apis.paths.api_v2_integration_capabilities_feature_store_project_key_environment_key_integration_key import ApiV2IntegrationCapabilitiesFeatureStoreProjectKeyEnvironmentKeyIntegrationKey
from launch_darkly_python_sdk.apis.paths.api_v2_integration_capabilities_feature_store_project_key_environment_key_integration_key_id import ApiV2IntegrationCapabilitiesFeatureStoreProjectKeyEnvironmentKeyIntegrationKeyId
from launch_darkly_python_sdk.apis.paths.api_v2_integration_capabilities_feature_store_project_key_environment_key_integration_key_id_validate import ApiV2IntegrationCapabilitiesFeatureStoreProjectKeyEnvironmentKeyIntegrationKeyIdValidate
from launch_darkly_python_sdk.apis.paths.api_v2_integrations_integration_key import ApiV2IntegrationsIntegrationKey
from launch_darkly_python_sdk.apis.paths.api_v2_integrations_integration_key_id import ApiV2IntegrationsIntegrationKeyId
from launch_darkly_python_sdk.apis.paths.api_v2_members import ApiV2Members
from launch_darkly_python_sdk.apis.paths.api_v2_members_id import ApiV2MembersId
from launch_darkly_python_sdk.apis.paths.api_v2_members_id_teams import ApiV2MembersIdTeams
from launch_darkly_python_sdk.apis.paths.api_v2_metrics_project_key import ApiV2MetricsProjectKey
from launch_darkly_python_sdk.apis.paths.api_v2_metrics_project_key_metric_key import ApiV2MetricsProjectKeyMetricKey
from launch_darkly_python_sdk.apis.paths.api_v2_oauth_clients import ApiV2OauthClients
from launch_darkly_python_sdk.apis.paths.api_v2_oauth_clients_client_id import ApiV2OauthClientsClientId
from launch_darkly_python_sdk.apis.paths.api_v2_openapi_json import ApiV2OpenapiJson
from launch_darkly_python_sdk.apis.paths.api_v2_projects import ApiV2Projects
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key import ApiV2ProjectsProjectKey
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_context_kinds import ApiV2ProjectsProjectKeyContextKinds
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_context_kinds_key import ApiV2ProjectsProjectKeyContextKindsKey
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_environments import ApiV2ProjectsProjectKeyEnvironments
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_environments_environment_key import ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKey
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_environments_environment_key_api_key import ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyApiKey
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_environments_environment_key_context_attributes import ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyContextAttributes
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_environments_environment_key_context_attributes_attribute_name import ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyContextAttributesAttributeName
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_environments_environment_key_context_instances_search import ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyContextInstancesSearch
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_environments_environment_key_context_instances_id import ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyContextInstancesId
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_environments_environment_key_contexts_search import ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyContextsSearch
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_environments_environment_key_contexts_context_kind_context_key_flags_feature_flag_key import ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyContextsContextKindContextKeyFlagsFeatureFlagKey
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_environments_environment_key_contexts_kind_key import ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyContextsKindKey
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_environments_environment_key_experiments import ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyExperiments
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_environments_environment_key_experiments_experiment_key import ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyExperimentsExperimentKey
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_environments_environment_key_experiments_experiment_key_iterations import ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyExperimentsExperimentKeyIterations
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_environments_environment_key_experiments_experiment_key_metric_groups_metric_group_key_results import ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyExperimentsExperimentKeyMetricGroupsMetricGroupKeyResults
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_environments_environment_key_experiments_experiment_key_metrics_metric_key_results import ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyExperimentsExperimentKeyMetricsMetricKeyResults
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_environments_environment_key_flags_evaluate import ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyFlagsEvaluate
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_environments_environment_key_followers import ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyFollowers
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_environments_environment_key_mobile_key import ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyMobileKey
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_environments_environment_key_segments_evaluate import ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeySegmentsEvaluate
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_experimentation_settings import ApiV2ProjectsProjectKeyExperimentationSettings
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_flag_defaults import ApiV2ProjectsProjectKeyFlagDefaults
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_flags_feature_flag_key_environments_environment_key_approval_requests import ApiV2ProjectsProjectKeyFlagsFeatureFlagKeyEnvironmentsEnvironmentKeyApprovalRequests
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_flags_feature_flag_key_environments_environment_key_approval_requests_flag_copy import ApiV2ProjectsProjectKeyFlagsFeatureFlagKeyEnvironmentsEnvironmentKeyApprovalRequestsFlagCopy
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_flags_feature_flag_key_environments_environment_key_approval_requests_id import ApiV2ProjectsProjectKeyFlagsFeatureFlagKeyEnvironmentsEnvironmentKeyApprovalRequestsId
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_flags_feature_flag_key_environments_environment_key_approval_requests_id_apply import ApiV2ProjectsProjectKeyFlagsFeatureFlagKeyEnvironmentsEnvironmentKeyApprovalRequestsIdApply
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_flags_feature_flag_key_environments_environment_key_approval_requests_id_reviews import ApiV2ProjectsProjectKeyFlagsFeatureFlagKeyEnvironmentsEnvironmentKeyApprovalRequestsIdReviews
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_flags_feature_flag_key_environments_environment_key_followers import ApiV2ProjectsProjectKeyFlagsFeatureFlagKeyEnvironmentsEnvironmentKeyFollowers
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_flags_feature_flag_key_environments_environment_key_followers_member_id import ApiV2ProjectsProjectKeyFlagsFeatureFlagKeyEnvironmentsEnvironmentKeyFollowersMemberId
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_flags_feature_flag_key_environments_environment_key_scheduled_changes import ApiV2ProjectsProjectKeyFlagsFeatureFlagKeyEnvironmentsEnvironmentKeyScheduledChanges
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_flags_feature_flag_key_environments_environment_key_scheduled_changes_id import ApiV2ProjectsProjectKeyFlagsFeatureFlagKeyEnvironmentsEnvironmentKeyScheduledChangesId
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_flags_feature_flag_key_environments_environment_key_workflows import ApiV2ProjectsProjectKeyFlagsFeatureFlagKeyEnvironmentsEnvironmentKeyWorkflows
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_flags_feature_flag_key_environments_environment_key_workflows_workflow_id import ApiV2ProjectsProjectKeyFlagsFeatureFlagKeyEnvironmentsEnvironmentKeyWorkflowsWorkflowId
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_flags_flag_key_environments_environment_key_migration_safety_issues import ApiV2ProjectsProjectKeyFlagsFlagKeyEnvironmentsEnvironmentKeyMigrationSafetyIssues
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_metric_groups import ApiV2ProjectsProjectKeyMetricGroups
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_metric_groups_metric_group_key import ApiV2ProjectsProjectKeyMetricGroupsMetricGroupKey
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_release_pipelines import ApiV2ProjectsProjectKeyReleasePipelines
from launch_darkly_python_sdk.apis.paths.api_v2_projects_project_key_release_pipelines_pipeline_key import ApiV2ProjectsProjectKeyReleasePipelinesPipelineKey
from launch_darkly_python_sdk.apis.paths.api_v2_public_ip_list import ApiV2PublicIpList
from launch_darkly_python_sdk.apis.paths.api_v2_roles import ApiV2Roles
from launch_darkly_python_sdk.apis.paths.api_v2_roles_custom_role_key import ApiV2RolesCustomRoleKey
from launch_darkly_python_sdk.apis.paths.api_v2_segments_project_key_environment_key import ApiV2SegmentsProjectKeyEnvironmentKey
from launch_darkly_python_sdk.apis.paths.api_v2_segments_project_key_environment_key_segment_key import ApiV2SegmentsProjectKeyEnvironmentKeySegmentKey
from launch_darkly_python_sdk.apis.paths.api_v2_segments_project_key_environment_key_segment_key_contexts import ApiV2SegmentsProjectKeyEnvironmentKeySegmentKeyContexts
from launch_darkly_python_sdk.apis.paths.api_v2_segments_project_key_environment_key_segment_key_contexts_context_key import ApiV2SegmentsProjectKeyEnvironmentKeySegmentKeyContextsContextKey
from launch_darkly_python_sdk.apis.paths.api_v2_segments_project_key_environment_key_segment_key_exports import ApiV2SegmentsProjectKeyEnvironmentKeySegmentKeyExports
from launch_darkly_python_sdk.apis.paths.api_v2_segments_project_key_environment_key_segment_key_exports_export_id import ApiV2SegmentsProjectKeyEnvironmentKeySegmentKeyExportsExportID
from launch_darkly_python_sdk.apis.paths.api_v2_segments_project_key_environment_key_segment_key_imports import ApiV2SegmentsProjectKeyEnvironmentKeySegmentKeyImports
from launch_darkly_python_sdk.apis.paths.api_v2_segments_project_key_environment_key_segment_key_imports_import_id import ApiV2SegmentsProjectKeyEnvironmentKeySegmentKeyImportsImportID
from launch_darkly_python_sdk.apis.paths.api_v2_segments_project_key_environment_key_segment_key_users import ApiV2SegmentsProjectKeyEnvironmentKeySegmentKeyUsers
from launch_darkly_python_sdk.apis.paths.api_v2_segments_project_key_environment_key_segment_key_users_user_key import ApiV2SegmentsProjectKeyEnvironmentKeySegmentKeyUsersUserKey
from launch_darkly_python_sdk.apis.paths.api_v2_segments_project_key_segment_key_expiring_targets_environment_key import ApiV2SegmentsProjectKeySegmentKeyExpiringTargetsEnvironmentKey
from launch_darkly_python_sdk.apis.paths.api_v2_segments_project_key_segment_key_expiring_user_targets_environment_key import ApiV2SegmentsProjectKeySegmentKeyExpiringUserTargetsEnvironmentKey
from launch_darkly_python_sdk.apis.paths.api_v2_tags import ApiV2Tags
from launch_darkly_python_sdk.apis.paths.api_v2_teams import ApiV2Teams
from launch_darkly_python_sdk.apis.paths.api_v2_teams_team_key import ApiV2TeamsTeamKey
from launch_darkly_python_sdk.apis.paths.api_v2_teams_team_key_maintainers import ApiV2TeamsTeamKeyMaintainers
from launch_darkly_python_sdk.apis.paths.api_v2_teams_team_key_members import ApiV2TeamsTeamKeyMembers
from launch_darkly_python_sdk.apis.paths.api_v2_teams_team_key_roles import ApiV2TeamsTeamKeyRoles
from launch_darkly_python_sdk.apis.paths.api_v2_templates import ApiV2Templates
from launch_darkly_python_sdk.apis.paths.api_v2_templates_template_key import ApiV2TemplatesTemplateKey
from launch_darkly_python_sdk.apis.paths.api_v2_tokens import ApiV2Tokens
from launch_darkly_python_sdk.apis.paths.api_v2_tokens_id import ApiV2TokensId
from launch_darkly_python_sdk.apis.paths.api_v2_tokens_id_reset import ApiV2TokensIdReset
from launch_darkly_python_sdk.apis.paths.api_v2_usage_evaluations_project_key_environment_key_feature_flag_key import ApiV2UsageEvaluationsProjectKeyEnvironmentKeyFeatureFlagKey
from launch_darkly_python_sdk.apis.paths.api_v2_usage_events_type import ApiV2UsageEventsType
from launch_darkly_python_sdk.apis.paths.api_v2_usage_experimentation_keys import ApiV2UsageExperimentationKeys
from launch_darkly_python_sdk.apis.paths.api_v2_usage_experimentation_units import ApiV2UsageExperimentationUnits
from launch_darkly_python_sdk.apis.paths.api_v2_usage_mau import ApiV2UsageMau
from launch_darkly_python_sdk.apis.paths.api_v2_usage_mau_bycategory import ApiV2UsageMauBycategory
from launch_darkly_python_sdk.apis.paths.api_v2_usage_mau_sdks import ApiV2UsageMauSdks
from launch_darkly_python_sdk.apis.paths.api_v2_usage_streams_source import ApiV2UsageStreamsSource
from launch_darkly_python_sdk.apis.paths.api_v2_usage_streams_source_bysdkversion import ApiV2UsageStreamsSourceBysdkversion
from launch_darkly_python_sdk.apis.paths.api_v2_usage_streams_source_sdkversions import ApiV2UsageStreamsSourceSdkversions
from launch_darkly_python_sdk.apis.paths.api_v2_user_attributes_project_key_environment_key import ApiV2UserAttributesProjectKeyEnvironmentKey
from launch_darkly_python_sdk.apis.paths.api_v2_user_search_project_key_environment_key import ApiV2UserSearchProjectKeyEnvironmentKey
from launch_darkly_python_sdk.apis.paths.api_v2_users_project_key_environment_key import ApiV2UsersProjectKeyEnvironmentKey
from launch_darkly_python_sdk.apis.paths.api_v2_users_project_key_environment_key_user_key import ApiV2UsersProjectKeyEnvironmentKeyUserKey
from launch_darkly_python_sdk.apis.paths.api_v2_users_project_key_environment_key_user_key_flags import ApiV2UsersProjectKeyEnvironmentKeyUserKeyFlags
from launch_darkly_python_sdk.apis.paths.api_v2_users_project_key_environment_key_user_key_flags_feature_flag_key import ApiV2UsersProjectKeyEnvironmentKeyUserKeyFlagsFeatureFlagKey
from launch_darkly_python_sdk.apis.paths.api_v2_users_project_key_user_key_expiring_user_targets_environment_key import ApiV2UsersProjectKeyUserKeyExpiringUserTargetsEnvironmentKey
from launch_darkly_python_sdk.apis.paths.api_v2_versions import ApiV2Versions
from launch_darkly_python_sdk.apis.paths.api_v2_webhooks import ApiV2Webhooks
from launch_darkly_python_sdk.apis.paths.api_v2_webhooks_id import ApiV2WebhooksId
from launch_darkly_python_sdk.apis.paths.api_v2_engineering_insights_charts_deployments_frequency import ApiV2EngineeringInsightsChartsDeploymentsFrequency
from launch_darkly_python_sdk.apis.paths.api_v2_engineering_insights_charts_flags_stale import ApiV2EngineeringInsightsChartsFlagsStale
from launch_darkly_python_sdk.apis.paths.api_v2_engineering_insights_charts_flags_status import ApiV2EngineeringInsightsChartsFlagsStatus
from launch_darkly_python_sdk.apis.paths.api_v2_engineering_insights_charts_lead_time import ApiV2EngineeringInsightsChartsLeadTime
from launch_darkly_python_sdk.apis.paths.api_v2_engineering_insights_charts_releases_frequency import ApiV2EngineeringInsightsChartsReleasesFrequency
from launch_darkly_python_sdk.apis.paths.api_v2_engineering_insights_deployment_events import ApiV2EngineeringInsightsDeploymentEvents
from launch_darkly_python_sdk.apis.paths.api_v2_engineering_insights_deployments import ApiV2EngineeringInsightsDeployments
from launch_darkly_python_sdk.apis.paths.api_v2_engineering_insights_deployments_deployment_id import ApiV2EngineeringInsightsDeploymentsDeploymentID
from launch_darkly_python_sdk.apis.paths.api_v2_engineering_insights_flag_events import ApiV2EngineeringInsightsFlagEvents
from launch_darkly_python_sdk.apis.paths.api_v2_engineering_insights_insights_group import ApiV2EngineeringInsightsInsightsGroup
from launch_darkly_python_sdk.apis.paths.api_v2_engineering_insights_insights_groups import ApiV2EngineeringInsightsInsightsGroups
from launch_darkly_python_sdk.apis.paths.api_v2_engineering_insights_insights_groups_insight_group_key import ApiV2EngineeringInsightsInsightsGroupsInsightGroupKey
from launch_darkly_python_sdk.apis.paths.api_v2_engineering_insights_insights_scores import ApiV2EngineeringInsightsInsightsScores
from launch_darkly_python_sdk.apis.paths.api_v2_engineering_insights_pull_requests import ApiV2EngineeringInsightsPullRequests
from launch_darkly_python_sdk.apis.paths.api_v2_engineering_insights_repositories import ApiV2EngineeringInsightsRepositories
from launch_darkly_python_sdk.apis.paths.api_v2_engineering_insights_repositories_projects import ApiV2EngineeringInsightsRepositoriesProjects
from launch_darkly_python_sdk.apis.paths.api_v2_engineering_insights_repositories_repository_key_projects_project_key import ApiV2EngineeringInsightsRepositoriesRepositoryKeyProjectsProjectKey

PathToApi = typing_extensions.TypedDict(
    'PathToApi',
    {
        PathValues.API_V2: ApiV2,
        PathValues.API_V2_ACCOUNT_RELAYAUTOCONFIGS: ApiV2AccountRelayAutoConfigs,
        PathValues.API_V2_ACCOUNT_RELAYAUTOCONFIGS_ID: ApiV2AccountRelayAutoConfigsId,
        PathValues.API_V2_ACCOUNT_RELAYAUTOCONFIGS_ID_RESET: ApiV2AccountRelayAutoConfigsIdReset,
        PathValues.API_V2_APPLICATIONS: ApiV2Applications,
        PathValues.API_V2_APPLICATIONS_APPLICATION_KEY: ApiV2ApplicationsApplicationKey,
        PathValues.API_V2_APPLICATIONS_APPLICATION_KEY_VERSIONS: ApiV2ApplicationsApplicationKeyVersions,
        PathValues.API_V2_APPLICATIONS_APPLICATION_KEY_VERSIONS_VERSION_KEY: ApiV2ApplicationsApplicationKeyVersionsVersionKey,
        PathValues.API_V2_APPROVALREQUESTS: ApiV2ApprovalRequests,
        PathValues.API_V2_APPROVALREQUESTS_ID: ApiV2ApprovalRequestsId,
        PathValues.API_V2_APPROVALREQUESTS_ID_APPLY: ApiV2ApprovalRequestsIdApply,
        PathValues.API_V2_APPROVALREQUESTS_ID_REVIEWS: ApiV2ApprovalRequestsIdReviews,
        PathValues.API_V2_AUDITLOG: ApiV2Auditlog,
        PathValues.API_V2_AUDITLOG_ID: ApiV2AuditlogId,
        PathValues.API_V2_CODEREFS_EXTINCTIONS: ApiV2CodeRefsExtinctions,
        PathValues.API_V2_CODEREFS_REPOSITORIES: ApiV2CodeRefsRepositories,
        PathValues.API_V2_CODEREFS_REPOSITORIES_REPO: ApiV2CodeRefsRepositoriesRepo,
        PathValues.API_V2_CODEREFS_REPOSITORIES_REPO_BRANCHDELETETASKS: ApiV2CodeRefsRepositoriesRepoBranchDeleteTasks,
        PathValues.API_V2_CODEREFS_REPOSITORIES_REPO_BRANCHES: ApiV2CodeRefsRepositoriesRepoBranches,
        PathValues.API_V2_CODEREFS_REPOSITORIES_REPO_BRANCHES_BRANCH: ApiV2CodeRefsRepositoriesRepoBranchesBranch,
        PathValues.API_V2_CODEREFS_REPOSITORIES_REPO_BRANCHES_BRANCH_EXTINCTIONEVENTS: ApiV2CodeRefsRepositoriesRepoBranchesBranchExtinctionEvents,
        PathValues.API_V2_CODEREFS_STATISTICS: ApiV2CodeRefsStatistics,
        PathValues.API_V2_CODEREFS_STATISTICS_PROJECT_KEY: ApiV2CodeRefsStatisticsProjectKey,
        PathValues.API_V2_DESTINATIONS: ApiV2Destinations,
        PathValues.API_V2_DESTINATIONS_PROJECT_KEY_ENVIRONMENT_KEY: ApiV2DestinationsProjectKeyEnvironmentKey,
        PathValues.API_V2_DESTINATIONS_PROJECT_KEY_ENVIRONMENT_KEY_ID: ApiV2DestinationsProjectKeyEnvironmentKeyId,
        PathValues.API_V2_FLAGLINKS_PROJECTS_PROJECT_KEY_FLAGS_FEATURE_FLAG_KEY: ApiV2FlagLinksProjectsProjectKeyFlagsFeatureFlagKey,
        PathValues.API_V2_FLAGLINKS_PROJECTS_PROJECT_KEY_FLAGS_FEATURE_FLAG_KEY_ID: ApiV2FlagLinksProjectsProjectKeyFlagsFeatureFlagKeyId,
        PathValues.API_V2_FLAGSTATUS_PROJECT_KEY_FEATURE_FLAG_KEY: ApiV2FlagStatusProjectKeyFeatureFlagKey,
        PathValues.API_V2_FLAGSTATUSES_PROJECT_KEY_ENVIRONMENT_KEY: ApiV2FlagStatusesProjectKeyEnvironmentKey,
        PathValues.API_V2_FLAGSTATUSES_PROJECT_KEY_ENVIRONMENT_KEY_FEATURE_FLAG_KEY: ApiV2FlagStatusesProjectKeyEnvironmentKeyFeatureFlagKey,
        PathValues.API_V2_FLAGS_PROJECT_KEY: ApiV2FlagsProjectKey,
        PathValues.API_V2_FLAGS_PROJECT_KEY_ENVIRONMENT_KEY_FEATURE_FLAG_KEY_DEPENDENTFLAGS: ApiV2FlagsProjectKeyEnvironmentKeyFeatureFlagKeyDependentFlags,
        PathValues.API_V2_FLAGS_PROJECT_KEY_FEATURE_FLAG_KEY: ApiV2FlagsProjectKeyFeatureFlagKey,
        PathValues.API_V2_FLAGS_PROJECT_KEY_FEATURE_FLAG_KEY_COPY: ApiV2FlagsProjectKeyFeatureFlagKeyCopy,
        PathValues.API_V2_FLAGS_PROJECT_KEY_FEATURE_FLAG_KEY_DEPENDENTFLAGS: ApiV2FlagsProjectKeyFeatureFlagKeyDependentFlags,
        PathValues.API_V2_FLAGS_PROJECT_KEY_FEATURE_FLAG_KEY_EXPERIMENTS_ENVIRONMENT_KEY_METRIC_KEY: ApiV2FlagsProjectKeyFeatureFlagKeyExperimentsEnvironmentKeyMetricKey,
        PathValues.API_V2_FLAGS_PROJECT_KEY_FEATURE_FLAG_KEY_EXPIRINGTARGETS_ENVIRONMENT_KEY: ApiV2FlagsProjectKeyFeatureFlagKeyExpiringTargetsEnvironmentKey,
        PathValues.API_V2_FLAGS_PROJECT_KEY_FEATURE_FLAG_KEY_EXPIRINGUSERTARGETS_ENVIRONMENT_KEY: ApiV2FlagsProjectKeyFeatureFlagKeyExpiringUserTargetsEnvironmentKey,
        PathValues.API_V2_FLAGS_PROJECT_KEY_FEATURE_FLAG_KEY_TRIGGERS_ENVIRONMENT_KEY: ApiV2FlagsProjectKeyFeatureFlagKeyTriggersEnvironmentKey,
        PathValues.API_V2_FLAGS_PROJECT_KEY_FEATURE_FLAG_KEY_TRIGGERS_ENVIRONMENT_KEY_ID: ApiV2FlagsProjectKeyFeatureFlagKeyTriggersEnvironmentKeyId,
        PathValues.API_V2_FLAGS_PROJECT_KEY_FLAG_KEY_RELEASE: ApiV2FlagsProjectKeyFlagKeyRelease,
        PathValues.API_V2_INTEGRATIONCAPABILITIES_BIGSEGMENTSTORE: ApiV2IntegrationCapabilitiesBigSegmentStore,
        PathValues.API_V2_INTEGRATIONCAPABILITIES_BIGSEGMENTSTORE_PROJECT_KEY_ENVIRONMENT_KEY_INTEGRATION_KEY: ApiV2IntegrationCapabilitiesBigSegmentStoreProjectKeyEnvironmentKeyIntegrationKey,
        PathValues.API_V2_INTEGRATIONCAPABILITIES_BIGSEGMENTSTORE_PROJECT_KEY_ENVIRONMENT_KEY_INTEGRATION_KEY_INTEGRATION_ID: ApiV2IntegrationCapabilitiesBigSegmentStoreProjectKeyEnvironmentKeyIntegrationKeyIntegrationId,
        PathValues.API_V2_INTEGRATIONCAPABILITIES_FEATURE_STORE: ApiV2IntegrationCapabilitiesFeatureStore,
        PathValues.API_V2_INTEGRATIONCAPABILITIES_FEATURE_STORE_PROJECT_KEY_ENVIRONMENT_KEY: ApiV2IntegrationCapabilitiesFeatureStoreProjectKeyEnvironmentKey,
        PathValues.API_V2_INTEGRATIONCAPABILITIES_FEATURE_STORE_PROJECT_KEY_ENVIRONMENT_KEY_INTEGRATION_KEY: ApiV2IntegrationCapabilitiesFeatureStoreProjectKeyEnvironmentKeyIntegrationKey,
        PathValues.API_V2_INTEGRATIONCAPABILITIES_FEATURE_STORE_PROJECT_KEY_ENVIRONMENT_KEY_INTEGRATION_KEY_ID: ApiV2IntegrationCapabilitiesFeatureStoreProjectKeyEnvironmentKeyIntegrationKeyId,
        PathValues.API_V2_INTEGRATIONCAPABILITIES_FEATURE_STORE_PROJECT_KEY_ENVIRONMENT_KEY_INTEGRATION_KEY_ID_VALIDATE: ApiV2IntegrationCapabilitiesFeatureStoreProjectKeyEnvironmentKeyIntegrationKeyIdValidate,
        PathValues.API_V2_INTEGRATIONS_INTEGRATION_KEY: ApiV2IntegrationsIntegrationKey,
        PathValues.API_V2_INTEGRATIONS_INTEGRATION_KEY_ID: ApiV2IntegrationsIntegrationKeyId,
        PathValues.API_V2_MEMBERS: ApiV2Members,
        PathValues.API_V2_MEMBERS_ID: ApiV2MembersId,
        PathValues.API_V2_MEMBERS_ID_TEAMS: ApiV2MembersIdTeams,
        PathValues.API_V2_METRICS_PROJECT_KEY: ApiV2MetricsProjectKey,
        PathValues.API_V2_METRICS_PROJECT_KEY_METRIC_KEY: ApiV2MetricsProjectKeyMetricKey,
        PathValues.API_V2_OAUTH_CLIENTS: ApiV2OauthClients,
        PathValues.API_V2_OAUTH_CLIENTS_CLIENT_ID: ApiV2OauthClientsClientId,
        PathValues.API_V2_OPENAPI_JSON: ApiV2OpenapiJson,
        PathValues.API_V2_PROJECTS: ApiV2Projects,
        PathValues.API_V2_PROJECTS_PROJECT_KEY: ApiV2ProjectsProjectKey,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_CONTEXTKINDS: ApiV2ProjectsProjectKeyContextKinds,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_CONTEXTKINDS_KEY: ApiV2ProjectsProjectKeyContextKindsKey,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS: ApiV2ProjectsProjectKeyEnvironments,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS_ENVIRONMENT_KEY: ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKey,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_API_KEY: ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyApiKey,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_CONTEXTATTRIBUTES: ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyContextAttributes,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_CONTEXTATTRIBUTES_ATTRIBUTE_NAME: ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyContextAttributesAttributeName,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_CONTEXTINSTANCES_SEARCH: ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyContextInstancesSearch,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_CONTEXTINSTANCES_ID: ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyContextInstancesId,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_CONTEXTS_SEARCH: ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyContextsSearch,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_CONTEXTS_CONTEXT_KIND_CONTEXT_KEY_FLAGS_FEATURE_FLAG_KEY: ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyContextsContextKindContextKeyFlagsFeatureFlagKey,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_CONTEXTS_KIND_KEY: ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyContextsKindKey,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_EXPERIMENTS: ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyExperiments,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_EXPERIMENTS_EXPERIMENT_KEY: ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyExperimentsExperimentKey,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_EXPERIMENTS_EXPERIMENT_KEY_ITERATIONS: ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyExperimentsExperimentKeyIterations,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_EXPERIMENTS_EXPERIMENT_KEY_METRICGROUPS_METRIC_GROUP_KEY_RESULTS: ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyExperimentsExperimentKeyMetricGroupsMetricGroupKeyResults,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_EXPERIMENTS_EXPERIMENT_KEY_METRICS_METRIC_KEY_RESULTS: ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyExperimentsExperimentKeyMetricsMetricKeyResults,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_FLAGS_EVALUATE: ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyFlagsEvaluate,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_FOLLOWERS: ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyFollowers,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_MOBILE_KEY: ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyMobileKey,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_SEGMENTS_EVALUATE: ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeySegmentsEvaluate,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_EXPERIMENTATIONSETTINGS: ApiV2ProjectsProjectKeyExperimentationSettings,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_FLAGDEFAULTS: ApiV2ProjectsProjectKeyFlagDefaults,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_FLAGS_FEATURE_FLAG_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_APPROVALREQUESTS: ApiV2ProjectsProjectKeyFlagsFeatureFlagKeyEnvironmentsEnvironmentKeyApprovalRequests,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_FLAGS_FEATURE_FLAG_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_APPROVALREQUESTSFLAGCOPY: ApiV2ProjectsProjectKeyFlagsFeatureFlagKeyEnvironmentsEnvironmentKeyApprovalRequestsFlagCopy,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_FLAGS_FEATURE_FLAG_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_APPROVALREQUESTS_ID: ApiV2ProjectsProjectKeyFlagsFeatureFlagKeyEnvironmentsEnvironmentKeyApprovalRequestsId,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_FLAGS_FEATURE_FLAG_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_APPROVALREQUESTS_ID_APPLY: ApiV2ProjectsProjectKeyFlagsFeatureFlagKeyEnvironmentsEnvironmentKeyApprovalRequestsIdApply,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_FLAGS_FEATURE_FLAG_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_APPROVALREQUESTS_ID_REVIEWS: ApiV2ProjectsProjectKeyFlagsFeatureFlagKeyEnvironmentsEnvironmentKeyApprovalRequestsIdReviews,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_FLAGS_FEATURE_FLAG_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_FOLLOWERS: ApiV2ProjectsProjectKeyFlagsFeatureFlagKeyEnvironmentsEnvironmentKeyFollowers,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_FLAGS_FEATURE_FLAG_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_FOLLOWERS_MEMBER_ID: ApiV2ProjectsProjectKeyFlagsFeatureFlagKeyEnvironmentsEnvironmentKeyFollowersMemberId,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_FLAGS_FEATURE_FLAG_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_SCHEDULEDCHANGES: ApiV2ProjectsProjectKeyFlagsFeatureFlagKeyEnvironmentsEnvironmentKeyScheduledChanges,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_FLAGS_FEATURE_FLAG_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_SCHEDULEDCHANGES_ID: ApiV2ProjectsProjectKeyFlagsFeatureFlagKeyEnvironmentsEnvironmentKeyScheduledChangesId,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_FLAGS_FEATURE_FLAG_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_WORKFLOWS: ApiV2ProjectsProjectKeyFlagsFeatureFlagKeyEnvironmentsEnvironmentKeyWorkflows,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_FLAGS_FEATURE_FLAG_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_WORKFLOWS_WORKFLOW_ID: ApiV2ProjectsProjectKeyFlagsFeatureFlagKeyEnvironmentsEnvironmentKeyWorkflowsWorkflowId,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_FLAGS_FLAG_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_MIGRATIONSAFETYISSUES: ApiV2ProjectsProjectKeyFlagsFlagKeyEnvironmentsEnvironmentKeyMigrationSafetyIssues,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_METRICGROUPS: ApiV2ProjectsProjectKeyMetricGroups,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_METRICGROUPS_METRIC_GROUP_KEY: ApiV2ProjectsProjectKeyMetricGroupsMetricGroupKey,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_RELEASEPIPELINES: ApiV2ProjectsProjectKeyReleasePipelines,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_RELEASEPIPELINES_PIPELINE_KEY: ApiV2ProjectsProjectKeyReleasePipelinesPipelineKey,
        PathValues.API_V2_PUBLICIPLIST: ApiV2PublicIpList,
        PathValues.API_V2_ROLES: ApiV2Roles,
        PathValues.API_V2_ROLES_CUSTOM_ROLE_KEY: ApiV2RolesCustomRoleKey,
        PathValues.API_V2_SEGMENTS_PROJECT_KEY_ENVIRONMENT_KEY: ApiV2SegmentsProjectKeyEnvironmentKey,
        PathValues.API_V2_SEGMENTS_PROJECT_KEY_ENVIRONMENT_KEY_SEGMENT_KEY: ApiV2SegmentsProjectKeyEnvironmentKeySegmentKey,
        PathValues.API_V2_SEGMENTS_PROJECT_KEY_ENVIRONMENT_KEY_SEGMENT_KEY_CONTEXTS: ApiV2SegmentsProjectKeyEnvironmentKeySegmentKeyContexts,
        PathValues.API_V2_SEGMENTS_PROJECT_KEY_ENVIRONMENT_KEY_SEGMENT_KEY_CONTEXTS_CONTEXT_KEY: ApiV2SegmentsProjectKeyEnvironmentKeySegmentKeyContextsContextKey,
        PathValues.API_V2_SEGMENTS_PROJECT_KEY_ENVIRONMENT_KEY_SEGMENT_KEY_EXPORTS: ApiV2SegmentsProjectKeyEnvironmentKeySegmentKeyExports,
        PathValues.API_V2_SEGMENTS_PROJECT_KEY_ENVIRONMENT_KEY_SEGMENT_KEY_EXPORTS_EXPORT_ID: ApiV2SegmentsProjectKeyEnvironmentKeySegmentKeyExportsExportID,
        PathValues.API_V2_SEGMENTS_PROJECT_KEY_ENVIRONMENT_KEY_SEGMENT_KEY_IMPORTS: ApiV2SegmentsProjectKeyEnvironmentKeySegmentKeyImports,
        PathValues.API_V2_SEGMENTS_PROJECT_KEY_ENVIRONMENT_KEY_SEGMENT_KEY_IMPORTS_IMPORT_ID: ApiV2SegmentsProjectKeyEnvironmentKeySegmentKeyImportsImportID,
        PathValues.API_V2_SEGMENTS_PROJECT_KEY_ENVIRONMENT_KEY_SEGMENT_KEY_USERS: ApiV2SegmentsProjectKeyEnvironmentKeySegmentKeyUsers,
        PathValues.API_V2_SEGMENTS_PROJECT_KEY_ENVIRONMENT_KEY_SEGMENT_KEY_USERS_USER_KEY: ApiV2SegmentsProjectKeyEnvironmentKeySegmentKeyUsersUserKey,
        PathValues.API_V2_SEGMENTS_PROJECT_KEY_SEGMENT_KEY_EXPIRINGTARGETS_ENVIRONMENT_KEY: ApiV2SegmentsProjectKeySegmentKeyExpiringTargetsEnvironmentKey,
        PathValues.API_V2_SEGMENTS_PROJECT_KEY_SEGMENT_KEY_EXPIRINGUSERTARGETS_ENVIRONMENT_KEY: ApiV2SegmentsProjectKeySegmentKeyExpiringUserTargetsEnvironmentKey,
        PathValues.API_V2_TAGS: ApiV2Tags,
        PathValues.API_V2_TEAMS: ApiV2Teams,
        PathValues.API_V2_TEAMS_TEAM_KEY: ApiV2TeamsTeamKey,
        PathValues.API_V2_TEAMS_TEAM_KEY_MAINTAINERS: ApiV2TeamsTeamKeyMaintainers,
        PathValues.API_V2_TEAMS_TEAM_KEY_MEMBERS: ApiV2TeamsTeamKeyMembers,
        PathValues.API_V2_TEAMS_TEAM_KEY_ROLES: ApiV2TeamsTeamKeyRoles,
        PathValues.API_V2_TEMPLATES: ApiV2Templates,
        PathValues.API_V2_TEMPLATES_TEMPLATE_KEY: ApiV2TemplatesTemplateKey,
        PathValues.API_V2_TOKENS: ApiV2Tokens,
        PathValues.API_V2_TOKENS_ID: ApiV2TokensId,
        PathValues.API_V2_TOKENS_ID_RESET: ApiV2TokensIdReset,
        PathValues.API_V2_USAGE_EVALUATIONS_PROJECT_KEY_ENVIRONMENT_KEY_FEATURE_FLAG_KEY: ApiV2UsageEvaluationsProjectKeyEnvironmentKeyFeatureFlagKey,
        PathValues.API_V2_USAGE_EVENTS_TYPE: ApiV2UsageEventsType,
        PathValues.API_V2_USAGE_EXPERIMENTATIONKEYS: ApiV2UsageExperimentationKeys,
        PathValues.API_V2_USAGE_EXPERIMENTATIONUNITS: ApiV2UsageExperimentationUnits,
        PathValues.API_V2_USAGE_MAU: ApiV2UsageMau,
        PathValues.API_V2_USAGE_MAU_BYCATEGORY: ApiV2UsageMauBycategory,
        PathValues.API_V2_USAGE_MAU_SDKS: ApiV2UsageMauSdks,
        PathValues.API_V2_USAGE_STREAMS_SOURCE: ApiV2UsageStreamsSource,
        PathValues.API_V2_USAGE_STREAMS_SOURCE_BYSDKVERSION: ApiV2UsageStreamsSourceBysdkversion,
        PathValues.API_V2_USAGE_STREAMS_SOURCE_SDKVERSIONS: ApiV2UsageStreamsSourceSdkversions,
        PathValues.API_V2_USERATTRIBUTES_PROJECT_KEY_ENVIRONMENT_KEY: ApiV2UserAttributesProjectKeyEnvironmentKey,
        PathValues.API_V2_USERSEARCH_PROJECT_KEY_ENVIRONMENT_KEY: ApiV2UserSearchProjectKeyEnvironmentKey,
        PathValues.API_V2_USERS_PROJECT_KEY_ENVIRONMENT_KEY: ApiV2UsersProjectKeyEnvironmentKey,
        PathValues.API_V2_USERS_PROJECT_KEY_ENVIRONMENT_KEY_USER_KEY: ApiV2UsersProjectKeyEnvironmentKeyUserKey,
        PathValues.API_V2_USERS_PROJECT_KEY_ENVIRONMENT_KEY_USER_KEY_FLAGS: ApiV2UsersProjectKeyEnvironmentKeyUserKeyFlags,
        PathValues.API_V2_USERS_PROJECT_KEY_ENVIRONMENT_KEY_USER_KEY_FLAGS_FEATURE_FLAG_KEY: ApiV2UsersProjectKeyEnvironmentKeyUserKeyFlagsFeatureFlagKey,
        PathValues.API_V2_USERS_PROJECT_KEY_USER_KEY_EXPIRINGUSERTARGETS_ENVIRONMENT_KEY: ApiV2UsersProjectKeyUserKeyExpiringUserTargetsEnvironmentKey,
        PathValues.API_V2_VERSIONS: ApiV2Versions,
        PathValues.API_V2_WEBHOOKS: ApiV2Webhooks,
        PathValues.API_V2_WEBHOOKS_ID: ApiV2WebhooksId,
        PathValues.API_V2_ENGINEERINGINSIGHTS_CHARTS_DEPLOYMENTS_FREQUENCY: ApiV2EngineeringInsightsChartsDeploymentsFrequency,
        PathValues.API_V2_ENGINEERINGINSIGHTS_CHARTS_FLAGS_STALE: ApiV2EngineeringInsightsChartsFlagsStale,
        PathValues.API_V2_ENGINEERINGINSIGHTS_CHARTS_FLAGS_STATUS: ApiV2EngineeringInsightsChartsFlagsStatus,
        PathValues.API_V2_ENGINEERINGINSIGHTS_CHARTS_LEADTIME: ApiV2EngineeringInsightsChartsLeadTime,
        PathValues.API_V2_ENGINEERINGINSIGHTS_CHARTS_RELEASES_FREQUENCY: ApiV2EngineeringInsightsChartsReleasesFrequency,
        PathValues.API_V2_ENGINEERINGINSIGHTS_DEPLOYMENTEVENTS: ApiV2EngineeringInsightsDeploymentEvents,
        PathValues.API_V2_ENGINEERINGINSIGHTS_DEPLOYMENTS: ApiV2EngineeringInsightsDeployments,
        PathValues.API_V2_ENGINEERINGINSIGHTS_DEPLOYMENTS_DEPLOYMENT_ID: ApiV2EngineeringInsightsDeploymentsDeploymentID,
        PathValues.API_V2_ENGINEERINGINSIGHTS_FLAGEVENTS: ApiV2EngineeringInsightsFlagEvents,
        PathValues.API_V2_ENGINEERINGINSIGHTS_INSIGHTS_GROUP: ApiV2EngineeringInsightsInsightsGroup,
        PathValues.API_V2_ENGINEERINGINSIGHTS_INSIGHTS_GROUPS: ApiV2EngineeringInsightsInsightsGroups,
        PathValues.API_V2_ENGINEERINGINSIGHTS_INSIGHTS_GROUPS_INSIGHT_GROUP_KEY: ApiV2EngineeringInsightsInsightsGroupsInsightGroupKey,
        PathValues.API_V2_ENGINEERINGINSIGHTS_INSIGHTS_SCORES: ApiV2EngineeringInsightsInsightsScores,
        PathValues.API_V2_ENGINEERINGINSIGHTS_PULLREQUESTS: ApiV2EngineeringInsightsPullRequests,
        PathValues.API_V2_ENGINEERINGINSIGHTS_REPOSITORIES: ApiV2EngineeringInsightsRepositories,
        PathValues.API_V2_ENGINEERINGINSIGHTS_REPOSITORIES_PROJECTS: ApiV2EngineeringInsightsRepositoriesProjects,
        PathValues.API_V2_ENGINEERINGINSIGHTS_REPOSITORIES_REPOSITORY_KEY_PROJECTS_PROJECT_KEY: ApiV2EngineeringInsightsRepositoriesRepositoryKeyProjectsProjectKey,
    }
)

path_to_api = PathToApi(
    {
        PathValues.API_V2: ApiV2,
        PathValues.API_V2_ACCOUNT_RELAYAUTOCONFIGS: ApiV2AccountRelayAutoConfigs,
        PathValues.API_V2_ACCOUNT_RELAYAUTOCONFIGS_ID: ApiV2AccountRelayAutoConfigsId,
        PathValues.API_V2_ACCOUNT_RELAYAUTOCONFIGS_ID_RESET: ApiV2AccountRelayAutoConfigsIdReset,
        PathValues.API_V2_APPLICATIONS: ApiV2Applications,
        PathValues.API_V2_APPLICATIONS_APPLICATION_KEY: ApiV2ApplicationsApplicationKey,
        PathValues.API_V2_APPLICATIONS_APPLICATION_KEY_VERSIONS: ApiV2ApplicationsApplicationKeyVersions,
        PathValues.API_V2_APPLICATIONS_APPLICATION_KEY_VERSIONS_VERSION_KEY: ApiV2ApplicationsApplicationKeyVersionsVersionKey,
        PathValues.API_V2_APPROVALREQUESTS: ApiV2ApprovalRequests,
        PathValues.API_V2_APPROVALREQUESTS_ID: ApiV2ApprovalRequestsId,
        PathValues.API_V2_APPROVALREQUESTS_ID_APPLY: ApiV2ApprovalRequestsIdApply,
        PathValues.API_V2_APPROVALREQUESTS_ID_REVIEWS: ApiV2ApprovalRequestsIdReviews,
        PathValues.API_V2_AUDITLOG: ApiV2Auditlog,
        PathValues.API_V2_AUDITLOG_ID: ApiV2AuditlogId,
        PathValues.API_V2_CODEREFS_EXTINCTIONS: ApiV2CodeRefsExtinctions,
        PathValues.API_V2_CODEREFS_REPOSITORIES: ApiV2CodeRefsRepositories,
        PathValues.API_V2_CODEREFS_REPOSITORIES_REPO: ApiV2CodeRefsRepositoriesRepo,
        PathValues.API_V2_CODEREFS_REPOSITORIES_REPO_BRANCHDELETETASKS: ApiV2CodeRefsRepositoriesRepoBranchDeleteTasks,
        PathValues.API_V2_CODEREFS_REPOSITORIES_REPO_BRANCHES: ApiV2CodeRefsRepositoriesRepoBranches,
        PathValues.API_V2_CODEREFS_REPOSITORIES_REPO_BRANCHES_BRANCH: ApiV2CodeRefsRepositoriesRepoBranchesBranch,
        PathValues.API_V2_CODEREFS_REPOSITORIES_REPO_BRANCHES_BRANCH_EXTINCTIONEVENTS: ApiV2CodeRefsRepositoriesRepoBranchesBranchExtinctionEvents,
        PathValues.API_V2_CODEREFS_STATISTICS: ApiV2CodeRefsStatistics,
        PathValues.API_V2_CODEREFS_STATISTICS_PROJECT_KEY: ApiV2CodeRefsStatisticsProjectKey,
        PathValues.API_V2_DESTINATIONS: ApiV2Destinations,
        PathValues.API_V2_DESTINATIONS_PROJECT_KEY_ENVIRONMENT_KEY: ApiV2DestinationsProjectKeyEnvironmentKey,
        PathValues.API_V2_DESTINATIONS_PROJECT_KEY_ENVIRONMENT_KEY_ID: ApiV2DestinationsProjectKeyEnvironmentKeyId,
        PathValues.API_V2_FLAGLINKS_PROJECTS_PROJECT_KEY_FLAGS_FEATURE_FLAG_KEY: ApiV2FlagLinksProjectsProjectKeyFlagsFeatureFlagKey,
        PathValues.API_V2_FLAGLINKS_PROJECTS_PROJECT_KEY_FLAGS_FEATURE_FLAG_KEY_ID: ApiV2FlagLinksProjectsProjectKeyFlagsFeatureFlagKeyId,
        PathValues.API_V2_FLAGSTATUS_PROJECT_KEY_FEATURE_FLAG_KEY: ApiV2FlagStatusProjectKeyFeatureFlagKey,
        PathValues.API_V2_FLAGSTATUSES_PROJECT_KEY_ENVIRONMENT_KEY: ApiV2FlagStatusesProjectKeyEnvironmentKey,
        PathValues.API_V2_FLAGSTATUSES_PROJECT_KEY_ENVIRONMENT_KEY_FEATURE_FLAG_KEY: ApiV2FlagStatusesProjectKeyEnvironmentKeyFeatureFlagKey,
        PathValues.API_V2_FLAGS_PROJECT_KEY: ApiV2FlagsProjectKey,
        PathValues.API_V2_FLAGS_PROJECT_KEY_ENVIRONMENT_KEY_FEATURE_FLAG_KEY_DEPENDENTFLAGS: ApiV2FlagsProjectKeyEnvironmentKeyFeatureFlagKeyDependentFlags,
        PathValues.API_V2_FLAGS_PROJECT_KEY_FEATURE_FLAG_KEY: ApiV2FlagsProjectKeyFeatureFlagKey,
        PathValues.API_V2_FLAGS_PROJECT_KEY_FEATURE_FLAG_KEY_COPY: ApiV2FlagsProjectKeyFeatureFlagKeyCopy,
        PathValues.API_V2_FLAGS_PROJECT_KEY_FEATURE_FLAG_KEY_DEPENDENTFLAGS: ApiV2FlagsProjectKeyFeatureFlagKeyDependentFlags,
        PathValues.API_V2_FLAGS_PROJECT_KEY_FEATURE_FLAG_KEY_EXPERIMENTS_ENVIRONMENT_KEY_METRIC_KEY: ApiV2FlagsProjectKeyFeatureFlagKeyExperimentsEnvironmentKeyMetricKey,
        PathValues.API_V2_FLAGS_PROJECT_KEY_FEATURE_FLAG_KEY_EXPIRINGTARGETS_ENVIRONMENT_KEY: ApiV2FlagsProjectKeyFeatureFlagKeyExpiringTargetsEnvironmentKey,
        PathValues.API_V2_FLAGS_PROJECT_KEY_FEATURE_FLAG_KEY_EXPIRINGUSERTARGETS_ENVIRONMENT_KEY: ApiV2FlagsProjectKeyFeatureFlagKeyExpiringUserTargetsEnvironmentKey,
        PathValues.API_V2_FLAGS_PROJECT_KEY_FEATURE_FLAG_KEY_TRIGGERS_ENVIRONMENT_KEY: ApiV2FlagsProjectKeyFeatureFlagKeyTriggersEnvironmentKey,
        PathValues.API_V2_FLAGS_PROJECT_KEY_FEATURE_FLAG_KEY_TRIGGERS_ENVIRONMENT_KEY_ID: ApiV2FlagsProjectKeyFeatureFlagKeyTriggersEnvironmentKeyId,
        PathValues.API_V2_FLAGS_PROJECT_KEY_FLAG_KEY_RELEASE: ApiV2FlagsProjectKeyFlagKeyRelease,
        PathValues.API_V2_INTEGRATIONCAPABILITIES_BIGSEGMENTSTORE: ApiV2IntegrationCapabilitiesBigSegmentStore,
        PathValues.API_V2_INTEGRATIONCAPABILITIES_BIGSEGMENTSTORE_PROJECT_KEY_ENVIRONMENT_KEY_INTEGRATION_KEY: ApiV2IntegrationCapabilitiesBigSegmentStoreProjectKeyEnvironmentKeyIntegrationKey,
        PathValues.API_V2_INTEGRATIONCAPABILITIES_BIGSEGMENTSTORE_PROJECT_KEY_ENVIRONMENT_KEY_INTEGRATION_KEY_INTEGRATION_ID: ApiV2IntegrationCapabilitiesBigSegmentStoreProjectKeyEnvironmentKeyIntegrationKeyIntegrationId,
        PathValues.API_V2_INTEGRATIONCAPABILITIES_FEATURE_STORE: ApiV2IntegrationCapabilitiesFeatureStore,
        PathValues.API_V2_INTEGRATIONCAPABILITIES_FEATURE_STORE_PROJECT_KEY_ENVIRONMENT_KEY: ApiV2IntegrationCapabilitiesFeatureStoreProjectKeyEnvironmentKey,
        PathValues.API_V2_INTEGRATIONCAPABILITIES_FEATURE_STORE_PROJECT_KEY_ENVIRONMENT_KEY_INTEGRATION_KEY: ApiV2IntegrationCapabilitiesFeatureStoreProjectKeyEnvironmentKeyIntegrationKey,
        PathValues.API_V2_INTEGRATIONCAPABILITIES_FEATURE_STORE_PROJECT_KEY_ENVIRONMENT_KEY_INTEGRATION_KEY_ID: ApiV2IntegrationCapabilitiesFeatureStoreProjectKeyEnvironmentKeyIntegrationKeyId,
        PathValues.API_V2_INTEGRATIONCAPABILITIES_FEATURE_STORE_PROJECT_KEY_ENVIRONMENT_KEY_INTEGRATION_KEY_ID_VALIDATE: ApiV2IntegrationCapabilitiesFeatureStoreProjectKeyEnvironmentKeyIntegrationKeyIdValidate,
        PathValues.API_V2_INTEGRATIONS_INTEGRATION_KEY: ApiV2IntegrationsIntegrationKey,
        PathValues.API_V2_INTEGRATIONS_INTEGRATION_KEY_ID: ApiV2IntegrationsIntegrationKeyId,
        PathValues.API_V2_MEMBERS: ApiV2Members,
        PathValues.API_V2_MEMBERS_ID: ApiV2MembersId,
        PathValues.API_V2_MEMBERS_ID_TEAMS: ApiV2MembersIdTeams,
        PathValues.API_V2_METRICS_PROJECT_KEY: ApiV2MetricsProjectKey,
        PathValues.API_V2_METRICS_PROJECT_KEY_METRIC_KEY: ApiV2MetricsProjectKeyMetricKey,
        PathValues.API_V2_OAUTH_CLIENTS: ApiV2OauthClients,
        PathValues.API_V2_OAUTH_CLIENTS_CLIENT_ID: ApiV2OauthClientsClientId,
        PathValues.API_V2_OPENAPI_JSON: ApiV2OpenapiJson,
        PathValues.API_V2_PROJECTS: ApiV2Projects,
        PathValues.API_V2_PROJECTS_PROJECT_KEY: ApiV2ProjectsProjectKey,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_CONTEXTKINDS: ApiV2ProjectsProjectKeyContextKinds,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_CONTEXTKINDS_KEY: ApiV2ProjectsProjectKeyContextKindsKey,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS: ApiV2ProjectsProjectKeyEnvironments,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS_ENVIRONMENT_KEY: ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKey,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_API_KEY: ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyApiKey,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_CONTEXTATTRIBUTES: ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyContextAttributes,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_CONTEXTATTRIBUTES_ATTRIBUTE_NAME: ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyContextAttributesAttributeName,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_CONTEXTINSTANCES_SEARCH: ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyContextInstancesSearch,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_CONTEXTINSTANCES_ID: ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyContextInstancesId,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_CONTEXTS_SEARCH: ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyContextsSearch,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_CONTEXTS_CONTEXT_KIND_CONTEXT_KEY_FLAGS_FEATURE_FLAG_KEY: ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyContextsContextKindContextKeyFlagsFeatureFlagKey,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_CONTEXTS_KIND_KEY: ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyContextsKindKey,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_EXPERIMENTS: ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyExperiments,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_EXPERIMENTS_EXPERIMENT_KEY: ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyExperimentsExperimentKey,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_EXPERIMENTS_EXPERIMENT_KEY_ITERATIONS: ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyExperimentsExperimentKeyIterations,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_EXPERIMENTS_EXPERIMENT_KEY_METRICGROUPS_METRIC_GROUP_KEY_RESULTS: ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyExperimentsExperimentKeyMetricGroupsMetricGroupKeyResults,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_EXPERIMENTS_EXPERIMENT_KEY_METRICS_METRIC_KEY_RESULTS: ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyExperimentsExperimentKeyMetricsMetricKeyResults,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_FLAGS_EVALUATE: ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyFlagsEvaluate,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_FOLLOWERS: ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyFollowers,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_MOBILE_KEY: ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyMobileKey,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_SEGMENTS_EVALUATE: ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeySegmentsEvaluate,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_EXPERIMENTATIONSETTINGS: ApiV2ProjectsProjectKeyExperimentationSettings,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_FLAGDEFAULTS: ApiV2ProjectsProjectKeyFlagDefaults,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_FLAGS_FEATURE_FLAG_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_APPROVALREQUESTS: ApiV2ProjectsProjectKeyFlagsFeatureFlagKeyEnvironmentsEnvironmentKeyApprovalRequests,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_FLAGS_FEATURE_FLAG_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_APPROVALREQUESTSFLAGCOPY: ApiV2ProjectsProjectKeyFlagsFeatureFlagKeyEnvironmentsEnvironmentKeyApprovalRequestsFlagCopy,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_FLAGS_FEATURE_FLAG_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_APPROVALREQUESTS_ID: ApiV2ProjectsProjectKeyFlagsFeatureFlagKeyEnvironmentsEnvironmentKeyApprovalRequestsId,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_FLAGS_FEATURE_FLAG_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_APPROVALREQUESTS_ID_APPLY: ApiV2ProjectsProjectKeyFlagsFeatureFlagKeyEnvironmentsEnvironmentKeyApprovalRequestsIdApply,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_FLAGS_FEATURE_FLAG_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_APPROVALREQUESTS_ID_REVIEWS: ApiV2ProjectsProjectKeyFlagsFeatureFlagKeyEnvironmentsEnvironmentKeyApprovalRequestsIdReviews,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_FLAGS_FEATURE_FLAG_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_FOLLOWERS: ApiV2ProjectsProjectKeyFlagsFeatureFlagKeyEnvironmentsEnvironmentKeyFollowers,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_FLAGS_FEATURE_FLAG_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_FOLLOWERS_MEMBER_ID: ApiV2ProjectsProjectKeyFlagsFeatureFlagKeyEnvironmentsEnvironmentKeyFollowersMemberId,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_FLAGS_FEATURE_FLAG_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_SCHEDULEDCHANGES: ApiV2ProjectsProjectKeyFlagsFeatureFlagKeyEnvironmentsEnvironmentKeyScheduledChanges,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_FLAGS_FEATURE_FLAG_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_SCHEDULEDCHANGES_ID: ApiV2ProjectsProjectKeyFlagsFeatureFlagKeyEnvironmentsEnvironmentKeyScheduledChangesId,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_FLAGS_FEATURE_FLAG_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_WORKFLOWS: ApiV2ProjectsProjectKeyFlagsFeatureFlagKeyEnvironmentsEnvironmentKeyWorkflows,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_FLAGS_FEATURE_FLAG_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_WORKFLOWS_WORKFLOW_ID: ApiV2ProjectsProjectKeyFlagsFeatureFlagKeyEnvironmentsEnvironmentKeyWorkflowsWorkflowId,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_FLAGS_FLAG_KEY_ENVIRONMENTS_ENVIRONMENT_KEY_MIGRATIONSAFETYISSUES: ApiV2ProjectsProjectKeyFlagsFlagKeyEnvironmentsEnvironmentKeyMigrationSafetyIssues,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_METRICGROUPS: ApiV2ProjectsProjectKeyMetricGroups,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_METRICGROUPS_METRIC_GROUP_KEY: ApiV2ProjectsProjectKeyMetricGroupsMetricGroupKey,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_RELEASEPIPELINES: ApiV2ProjectsProjectKeyReleasePipelines,
        PathValues.API_V2_PROJECTS_PROJECT_KEY_RELEASEPIPELINES_PIPELINE_KEY: ApiV2ProjectsProjectKeyReleasePipelinesPipelineKey,
        PathValues.API_V2_PUBLICIPLIST: ApiV2PublicIpList,
        PathValues.API_V2_ROLES: ApiV2Roles,
        PathValues.API_V2_ROLES_CUSTOM_ROLE_KEY: ApiV2RolesCustomRoleKey,
        PathValues.API_V2_SEGMENTS_PROJECT_KEY_ENVIRONMENT_KEY: ApiV2SegmentsProjectKeyEnvironmentKey,
        PathValues.API_V2_SEGMENTS_PROJECT_KEY_ENVIRONMENT_KEY_SEGMENT_KEY: ApiV2SegmentsProjectKeyEnvironmentKeySegmentKey,
        PathValues.API_V2_SEGMENTS_PROJECT_KEY_ENVIRONMENT_KEY_SEGMENT_KEY_CONTEXTS: ApiV2SegmentsProjectKeyEnvironmentKeySegmentKeyContexts,
        PathValues.API_V2_SEGMENTS_PROJECT_KEY_ENVIRONMENT_KEY_SEGMENT_KEY_CONTEXTS_CONTEXT_KEY: ApiV2SegmentsProjectKeyEnvironmentKeySegmentKeyContextsContextKey,
        PathValues.API_V2_SEGMENTS_PROJECT_KEY_ENVIRONMENT_KEY_SEGMENT_KEY_EXPORTS: ApiV2SegmentsProjectKeyEnvironmentKeySegmentKeyExports,
        PathValues.API_V2_SEGMENTS_PROJECT_KEY_ENVIRONMENT_KEY_SEGMENT_KEY_EXPORTS_EXPORT_ID: ApiV2SegmentsProjectKeyEnvironmentKeySegmentKeyExportsExportID,
        PathValues.API_V2_SEGMENTS_PROJECT_KEY_ENVIRONMENT_KEY_SEGMENT_KEY_IMPORTS: ApiV2SegmentsProjectKeyEnvironmentKeySegmentKeyImports,
        PathValues.API_V2_SEGMENTS_PROJECT_KEY_ENVIRONMENT_KEY_SEGMENT_KEY_IMPORTS_IMPORT_ID: ApiV2SegmentsProjectKeyEnvironmentKeySegmentKeyImportsImportID,
        PathValues.API_V2_SEGMENTS_PROJECT_KEY_ENVIRONMENT_KEY_SEGMENT_KEY_USERS: ApiV2SegmentsProjectKeyEnvironmentKeySegmentKeyUsers,
        PathValues.API_V2_SEGMENTS_PROJECT_KEY_ENVIRONMENT_KEY_SEGMENT_KEY_USERS_USER_KEY: ApiV2SegmentsProjectKeyEnvironmentKeySegmentKeyUsersUserKey,
        PathValues.API_V2_SEGMENTS_PROJECT_KEY_SEGMENT_KEY_EXPIRINGTARGETS_ENVIRONMENT_KEY: ApiV2SegmentsProjectKeySegmentKeyExpiringTargetsEnvironmentKey,
        PathValues.API_V2_SEGMENTS_PROJECT_KEY_SEGMENT_KEY_EXPIRINGUSERTARGETS_ENVIRONMENT_KEY: ApiV2SegmentsProjectKeySegmentKeyExpiringUserTargetsEnvironmentKey,
        PathValues.API_V2_TAGS: ApiV2Tags,
        PathValues.API_V2_TEAMS: ApiV2Teams,
        PathValues.API_V2_TEAMS_TEAM_KEY: ApiV2TeamsTeamKey,
        PathValues.API_V2_TEAMS_TEAM_KEY_MAINTAINERS: ApiV2TeamsTeamKeyMaintainers,
        PathValues.API_V2_TEAMS_TEAM_KEY_MEMBERS: ApiV2TeamsTeamKeyMembers,
        PathValues.API_V2_TEAMS_TEAM_KEY_ROLES: ApiV2TeamsTeamKeyRoles,
        PathValues.API_V2_TEMPLATES: ApiV2Templates,
        PathValues.API_V2_TEMPLATES_TEMPLATE_KEY: ApiV2TemplatesTemplateKey,
        PathValues.API_V2_TOKENS: ApiV2Tokens,
        PathValues.API_V2_TOKENS_ID: ApiV2TokensId,
        PathValues.API_V2_TOKENS_ID_RESET: ApiV2TokensIdReset,
        PathValues.API_V2_USAGE_EVALUATIONS_PROJECT_KEY_ENVIRONMENT_KEY_FEATURE_FLAG_KEY: ApiV2UsageEvaluationsProjectKeyEnvironmentKeyFeatureFlagKey,
        PathValues.API_V2_USAGE_EVENTS_TYPE: ApiV2UsageEventsType,
        PathValues.API_V2_USAGE_EXPERIMENTATIONKEYS: ApiV2UsageExperimentationKeys,
        PathValues.API_V2_USAGE_EXPERIMENTATIONUNITS: ApiV2UsageExperimentationUnits,
        PathValues.API_V2_USAGE_MAU: ApiV2UsageMau,
        PathValues.API_V2_USAGE_MAU_BYCATEGORY: ApiV2UsageMauBycategory,
        PathValues.API_V2_USAGE_MAU_SDKS: ApiV2UsageMauSdks,
        PathValues.API_V2_USAGE_STREAMS_SOURCE: ApiV2UsageStreamsSource,
        PathValues.API_V2_USAGE_STREAMS_SOURCE_BYSDKVERSION: ApiV2UsageStreamsSourceBysdkversion,
        PathValues.API_V2_USAGE_STREAMS_SOURCE_SDKVERSIONS: ApiV2UsageStreamsSourceSdkversions,
        PathValues.API_V2_USERATTRIBUTES_PROJECT_KEY_ENVIRONMENT_KEY: ApiV2UserAttributesProjectKeyEnvironmentKey,
        PathValues.API_V2_USERSEARCH_PROJECT_KEY_ENVIRONMENT_KEY: ApiV2UserSearchProjectKeyEnvironmentKey,
        PathValues.API_V2_USERS_PROJECT_KEY_ENVIRONMENT_KEY: ApiV2UsersProjectKeyEnvironmentKey,
        PathValues.API_V2_USERS_PROJECT_KEY_ENVIRONMENT_KEY_USER_KEY: ApiV2UsersProjectKeyEnvironmentKeyUserKey,
        PathValues.API_V2_USERS_PROJECT_KEY_ENVIRONMENT_KEY_USER_KEY_FLAGS: ApiV2UsersProjectKeyEnvironmentKeyUserKeyFlags,
        PathValues.API_V2_USERS_PROJECT_KEY_ENVIRONMENT_KEY_USER_KEY_FLAGS_FEATURE_FLAG_KEY: ApiV2UsersProjectKeyEnvironmentKeyUserKeyFlagsFeatureFlagKey,
        PathValues.API_V2_USERS_PROJECT_KEY_USER_KEY_EXPIRINGUSERTARGETS_ENVIRONMENT_KEY: ApiV2UsersProjectKeyUserKeyExpiringUserTargetsEnvironmentKey,
        PathValues.API_V2_VERSIONS: ApiV2Versions,
        PathValues.API_V2_WEBHOOKS: ApiV2Webhooks,
        PathValues.API_V2_WEBHOOKS_ID: ApiV2WebhooksId,
        PathValues.API_V2_ENGINEERINGINSIGHTS_CHARTS_DEPLOYMENTS_FREQUENCY: ApiV2EngineeringInsightsChartsDeploymentsFrequency,
        PathValues.API_V2_ENGINEERINGINSIGHTS_CHARTS_FLAGS_STALE: ApiV2EngineeringInsightsChartsFlagsStale,
        PathValues.API_V2_ENGINEERINGINSIGHTS_CHARTS_FLAGS_STATUS: ApiV2EngineeringInsightsChartsFlagsStatus,
        PathValues.API_V2_ENGINEERINGINSIGHTS_CHARTS_LEADTIME: ApiV2EngineeringInsightsChartsLeadTime,
        PathValues.API_V2_ENGINEERINGINSIGHTS_CHARTS_RELEASES_FREQUENCY: ApiV2EngineeringInsightsChartsReleasesFrequency,
        PathValues.API_V2_ENGINEERINGINSIGHTS_DEPLOYMENTEVENTS: ApiV2EngineeringInsightsDeploymentEvents,
        PathValues.API_V2_ENGINEERINGINSIGHTS_DEPLOYMENTS: ApiV2EngineeringInsightsDeployments,
        PathValues.API_V2_ENGINEERINGINSIGHTS_DEPLOYMENTS_DEPLOYMENT_ID: ApiV2EngineeringInsightsDeploymentsDeploymentID,
        PathValues.API_V2_ENGINEERINGINSIGHTS_FLAGEVENTS: ApiV2EngineeringInsightsFlagEvents,
        PathValues.API_V2_ENGINEERINGINSIGHTS_INSIGHTS_GROUP: ApiV2EngineeringInsightsInsightsGroup,
        PathValues.API_V2_ENGINEERINGINSIGHTS_INSIGHTS_GROUPS: ApiV2EngineeringInsightsInsightsGroups,
        PathValues.API_V2_ENGINEERINGINSIGHTS_INSIGHTS_GROUPS_INSIGHT_GROUP_KEY: ApiV2EngineeringInsightsInsightsGroupsInsightGroupKey,
        PathValues.API_V2_ENGINEERINGINSIGHTS_INSIGHTS_SCORES: ApiV2EngineeringInsightsInsightsScores,
        PathValues.API_V2_ENGINEERINGINSIGHTS_PULLREQUESTS: ApiV2EngineeringInsightsPullRequests,
        PathValues.API_V2_ENGINEERINGINSIGHTS_REPOSITORIES: ApiV2EngineeringInsightsRepositories,
        PathValues.API_V2_ENGINEERINGINSIGHTS_REPOSITORIES_PROJECTS: ApiV2EngineeringInsightsRepositoriesProjects,
        PathValues.API_V2_ENGINEERINGINSIGHTS_REPOSITORIES_REPOSITORY_KEY_PROJECTS_PROJECT_KEY: ApiV2EngineeringInsightsRepositoriesRepositoryKeyProjectsProjectKey,
    }
)
