from launch_darkly_python_sdk.paths.api_v2_projects_project_key_environments_environment_key_context_instances_id.get import ApiForget
from launch_darkly_python_sdk.paths.api_v2_projects_project_key_environments_environment_key_context_instances_id.delete import ApiFordelete


class ApiV2ProjectsProjectKeyEnvironmentsEnvironmentKeyContextInstancesId(
    ApiForget,
    ApiFordelete,
):
    pass
