from launch_darkly_python_sdk.paths.api_v2_segments_project_key_segment_key_expiring_user_targets_environment_key.get import ApiForget
from launch_darkly_python_sdk.paths.api_v2_segments_project_key_segment_key_expiring_user_targets_environment_key.patch import ApiForpatch


class ApiV2SegmentsProjectKeySegmentKeyExpiringUserTargetsEnvironmentKey(
    ApiForget,
    ApiForpatch,
):
    pass
