from launch_darkly_python_sdk.paths.api_v2_projects_project_key_flags_feature_flag_key_environments_environment_key_workflows.get import ApiForget
from launch_darkly_python_sdk.paths.api_v2_projects_project_key_flags_feature_flag_key_environments_environment_key_workflows.post import ApiForpost


class ApiV2ProjectsProjectKeyFlagsFeatureFlagKeyEnvironmentsEnvironmentKeyWorkflows(
    ApiForget,
    ApiForpost,
):
    pass
