from launch_darkly_python_sdk.paths.api_v2_integration_capabilities_feature_store_project_key_environment_key_integration_key.post import ApiForpost


class ApiV2IntegrationCapabilitiesFeatureStoreProjectKeyEnvironmentKeyIntegrationKey(
    ApiForpost,
):
    pass
