from launch_darkly_python_sdk.paths.api_v2_flags_project_key_feature_flag_key_triggers_environment_key_id.get import ApiForget
from launch_darkly_python_sdk.paths.api_v2_flags_project_key_feature_flag_key_triggers_environment_key_id.delete import ApiFordelete
from launch_darkly_python_sdk.paths.api_v2_flags_project_key_feature_flag_key_triggers_environment_key_id.patch import ApiForpatch


class ApiV2FlagsProjectKeyFeatureFlagKeyTriggersEnvironmentKeyId(
    ApiForget,
    ApiFordelete,
    ApiForpatch,
):
    pass
