from launch_darkly_python_sdk.paths.api_v2_projects_project_key_flags_flag_key_environments_environment_key_migration_safety_issues.post import ApiForpost


class ApiV2ProjectsProjectKeyFlagsFlagKeyEnvironmentsEnvironmentKeyMigrationSafetyIssues(
    ApiForpost,
):
    pass
