from launch_darkly_python_sdk.paths.api_v2_integration_capabilities_feature_store_project_key_environment_key_integration_key_id.get import ApiForget
from launch_darkly_python_sdk.paths.api_v2_integration_capabilities_feature_store_project_key_environment_key_integration_key_id.delete import ApiFordelete
from launch_darkly_python_sdk.paths.api_v2_integration_capabilities_feature_store_project_key_environment_key_integration_key_id.patch import ApiForpatch


class ApiV2IntegrationCapabilitiesFeatureStoreProjectKeyEnvironmentKeyIntegrationKeyId(
    ApiForget,
    ApiFordelete,
    ApiForpatch,
):
    pass
