from launch_darkly_python_sdk.paths.api_v2_projects_project_key_flags_feature_flag_key_environments_environment_key_approval_requests_id.get import ApiForget
from launch_darkly_python_sdk.paths.api_v2_projects_project_key_flags_feature_flag_key_environments_environment_key_approval_requests_id.delete import ApiFordelete


class ApiV2ProjectsProjectKeyFlagsFeatureFlagKeyEnvironmentsEnvironmentKeyApprovalRequestsId(
    ApiForget,
    ApiFordelete,
):
    pass
