from launch_darkly_python_sdk.paths.api_v2_projects_project_key_flags_feature_flag_key_environments_environment_key_scheduled_changes_id.get import ApiForget
from launch_darkly_python_sdk.paths.api_v2_projects_project_key_flags_feature_flag_key_environments_environment_key_scheduled_changes_id.delete import ApiFordelete
from launch_darkly_python_sdk.paths.api_v2_projects_project_key_flags_feature_flag_key_environments_environment_key_scheduled_changes_id.patch import ApiForpatch


class ApiV2ProjectsProjectKeyFlagsFeatureFlagKeyEnvironmentsEnvironmentKeyScheduledChangesId(
    ApiForget,
    ApiFordelete,
    ApiForpatch,
):
    pass
